server:
  port: 8081

jwt:
  secret: mysecurejwtsecretkeyformyproject123456 #should be 32+ characters
  expiration: 3600000 

spring:
  profiles:
    active: dev
  datasource:
    url : jdbc:mysql://localhost:3306/auth_service
    username: root
    password: abhishek
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
